package com.creativeai.agentteam.model.enums;

public enum TaskType {
    EMAIL_RESPONSE, EMAIL_CLASSIFICATION, EMAIL_FORWARD,
    SOCIAL_POST, SOCIAL_REPLY, SOCIAL_ANALYTICS,
    PROSPECT_SEARCH, PROSPECT_QUALIFY, PROSPECT_OUTREACH,
    CAMPAIGN_CREATE, CONTENT_GENERATE, SEO_OPTIMIZE,
    TICKET_HANDLE, TICKET_ESCALATE, FAQ_UPDATE,
    DOCUMENT_INGEST, DOCUMENT_SEARCH, DOCUMENT_SUMMARIZE,
    CV_CREATE, CV_ANALYZE, CV_OPTIMIZE,
    IMAGE_GENERATE, IMAGE_EDIT, IMAGE_UPSCALE,
    VIDEO_GENERATE, VIDEO_TRANSCRIBE, VIDEO_EDIT,
    ANIMATION_CREATE, ANIMATION_RENDER,
    AD_SPOT_GENERATE, AD_SPOT_RENDER,
    SECURITY_SCAN, SECURITY_AUDIT, SECRETS_SCAN,
    DOCUMENT_EDIT, DOCUMENT_CONVERT, TEMPLATE_FILL,
    WORKFLOW_STEP, REPORT_GENERATE, GENERAL,
    PRESENTATION_CREATE, SOCIAL_CONTENT, ACCOUNTING_REPORT, DOCUMENT_PDF,
    SCHEDULED_TASK, WHATSAPP_TASK, TELEGRAM_TASK,
    PRODUCT_PROMOTION
}
